package com.mobilab.accountservice.bussiness.CurrencyExchage;

import java.util.HashMap;

public class Rates {
	private Double AED;
	private Double AFN;
	private Double ALL;
	private Double AMD;
	private Double ANG;
	private Double AOA;
	private Double ARS;
	private Double AUD;
	private Double AWG;
	private Double AZM;
	private Double BAM;
	private Double BBD;
	private Double BDT;
	private Double BGN;
	private Double BHD;
	private Double BIF;
	private Double BMD;
	private Double BND;
	private Double BOB;
	private Double BOV;
	private Double BRL;
	private Double BSD;
	private Double BTN;
	private Double BWP;
	private Double BYR;
	private Double BZD;
	private Double CAD;
	private Double CDF;
	private Double CHF;
	private Double CLF;
	private Double CLP;
	private Double CNY;
	private Double COP;
	private Double COU;
	private Double CRC;
	private Double CSD;
	private Double CUP;
	private Double CVE;
	private Double CYP;
	private Double CZK;
	private Double DJF;
	private Double DKK;
	private Double DOP;
	private Double DZD;
	private Double ECS;
	private Double ECV;
	private Double EEK;
	private Double EGP;
	private Double ERN;
	private Double ETB;
	private Double EUR;
	private Double FJD;
	private Double FKP;
	private Double GBP;
	private Double GEL;
	private Double GHC;
	private Double GIP;
	private Double GMD;
	private Double GNF;
	private Double GTQ;
	private Double GWP;
	private Double GYD;
	private Double HKD;
	private Double HNL;
	private Double HRK;
	private Double HTG;
	private Double HUF;
	private Double IDR;
	private Double ILS;
	private Double INR;
	private Double IQD;
	private Double IRR;
	private Double ISK;
	private Double JMD;
	private Double JOD;
	private Double JPY;
	private Double KES;
	private Double KGS;
	private Double KHR;
	private Double KMF;
	private Double KPW;
	private Double KRW;
	private Double KWD;
	private Double KYD;
	private Double KZT;
	private Double LAK;
	private Double LBP;
	private Double LKR;
	private Double LRD;
	private Double LSL;
	private Double LTL;
	private Double LVL;
	private Double LYD;
	private Double MAD;
	private Double MDL;
	private Double MGA;
	private Double MGF;
	private Double MKD;
	private Double MMK;
	private Double MNT;
	private Double MOP;
	private Double MRO;
	private Double MTL;
	private Double MUR;
	private Double MVR;
	private Double MWK;
	private Double MXN;
	private Double MXV;
	private Double MYR;
	private Double MZM;
	private Double NAD;
	private Double NGN;
	private Double NIO;
	private Double NOK;
	private Double NPR;
	private Double NZD;
	private Double OMR;
	private Double PAB;
	private Double PEN;
	private Double PGK;
	private Double PHP;
	private Double PKR;
	private Double PLN;
	private Double PYG;
	private Double QAR;
	private Double ROL;
	private Double RON;
	private Double RUB;
	private Double RUR;
	private Double RWF;
	private Double SAR;
	private Double SBD;
	private Double SCR;
	private Double SDD;
	private Double SEK;
	private Double SGD;
	private Double SHP;
	private Double SIT;
	//	private Double SKK;
	private Double SLL;
	private Double SOS;
	private Double SRD;
	private Double STD;
	private Double SVC;
	private Double SYP;
	private Double SZL;
	private Double THB;
	private Double TJS;
	private Double TMM;
	private Double TND;
	private Double TOP;
	private Double TRY;
	private Double TTD;
	private Double TWD;
	private Double TZS;
	private Double UAH;
	private Double UGX;
	private Double USD;
	private Double USN;
	private Double USS;
	private Double UYU;
	private Double UZS;
	private Double VEB;
	private Double VND;
	private Double VUV;
	private Double WST;
	private Double XAF;
	private Double XCD;
	private Double XOF;
	private Double XPF;
	private Double YER;
	private Double ZAR;
	private Double ZMK;
	private Double ZWD;

	private HashMap<String, Double> rates = null;

	public HashMap<String, Double> getRates() {
		if (rates == null) {
			rates = new HashMap<String, Double>();
			rates.put("AED", AED);
			rates.put("AFN", AFN);
			rates.put("ALL", ALL);
			rates.put("AMD", AMD);
			rates.put("ANG", ANG);
			rates.put("AOA", AOA);
			rates.put("ARS", ARS);
			rates.put("AUD", AUD);
			rates.put("AWG", AWG);
			rates.put("AZM", AZM);
			rates.put("BAM", BAM);
			rates.put("BBD", BBD);
			rates.put("BDT", BDT);
			rates.put("BGN", BGN);
			rates.put("BHD", BHD);
			rates.put("BIF", BIF);
			rates.put("BMD", BMD);
			rates.put("BND", BND);
			rates.put("BOB", BOB);
			rates.put("BOV", BOV);
			rates.put("BRL", BRL);
			rates.put("BSD", BSD);
			rates.put("BTN", BTN);
			rates.put("BWP", BWP);
			rates.put("BYR", BYR);
			rates.put("BZD", BZD);
			rates.put("CAD", CAD);
			rates.put("CDF", CDF);
			rates.put("CHF", CHF);
			rates.put("CLF", CLF);
			rates.put("CLP", CLP);
			rates.put("CNY", CNY);
			rates.put("COP", COP);
			rates.put("COU", COU);
			rates.put("CRC", CRC);
			rates.put("CSD", CSD);
			rates.put("CUP", CUP);
			rates.put("CVE", CVE);
			rates.put("CYP", CYP);
			rates.put("CZK", CZK);
			rates.put("DJF", DJF);
			rates.put("DKK", DKK);
			rates.put("DOP", DOP);
			rates.put("DZD", DZD);
			rates.put("ECS", ECS);
			rates.put("ECV", ECV);
			rates.put("EEK", EEK);
			rates.put("EGP", EGP);
			rates.put("ERN", ERN);
			rates.put("ETB", ETB);
			rates.put("EUR", EUR);
			rates.put("FJD", FJD);
			rates.put("FKP", FKP);
			rates.put("GBP", GBP);
			rates.put("GEL", GEL);
			rates.put("GHC", GHC);
			rates.put("GIP", GIP);
			rates.put("GMD", GMD);
			rates.put("GNF", GNF);
			rates.put("GTQ", GTQ);
			rates.put("GWP", GWP);
			rates.put("GYD", GYD);
			rates.put("HKD", HKD);
			rates.put("HNL", HNL);
			rates.put("HRK", HRK);
			rates.put("HTG", HTG);
			rates.put("HUF", HUF);
			rates.put("IDR", IDR);
			rates.put("ILS", ILS);
			rates.put("INR", INR);
			rates.put("IQD", IQD);
			rates.put("IRR", IRR);
			rates.put("ISK", ISK);
			rates.put("JMD", JMD);
			rates.put("JOD", JOD);
			rates.put("JPY", JPY);
			rates.put("KES", KES);
			rates.put("KGS", KGS);
			rates.put("KHR", KHR);
			rates.put("KMF", KMF);
			rates.put("KPW", KPW);
			rates.put("KRW", KRW);
			rates.put("KWD", KWD);
			rates.put("KYD", KYD);
			rates.put("KZT", KZT);
			rates.put("LAK", LAK);
			rates.put("LBP", LBP);
			rates.put("LKR", LKR);
			rates.put("LRD", LRD);
			rates.put("LSL", LSL);
			rates.put("LTL", LTL);
			rates.put("LVL", LVL);
			rates.put("LYD", LYD);
			rates.put("MAD", MAD);
			rates.put("MDL", MDL);
			rates.put("MGA", MGA);
			rates.put("MGF", MGF);
			rates.put("MKD", MKD);
			rates.put("MMK", MMK);
			rates.put("MNT", MNT);
			rates.put("MOP", MOP);
			rates.put("MRO", MRO);
			rates.put("MTL", MTL);
			rates.put("MUR", MUR);
			rates.put("MVR", MVR);
			rates.put("MWK", MWK);
			rates.put("MXN", MXN);
			rates.put("MXV", MXV);
			rates.put("MYR", MYR);
			rates.put("MZM", MZM);
			rates.put("NAD", NAD);
			rates.put("NGN", NGN);
			rates.put("NIO", NIO);
			rates.put("NOK", NOK);
			rates.put("NPR", NPR);
			rates.put("NZD", NZD);
			rates.put("OMR", OMR);
			rates.put("PAB", PAB);
			rates.put("PEN", PEN);
			rates.put("PGK", PGK);
			rates.put("PHP", PHP);
			rates.put("PKR", PKR);
			rates.put("PLN", PLN);
			rates.put("PYG", PYG);
			rates.put("QAR", QAR);
			rates.put("ROL", ROL);
			rates.put("RON", RON);
			rates.put("RUB", RUB);
			rates.put("RUR", RUR);
			rates.put("RWF", RWF);
			rates.put("SAR", SAR);
			rates.put("SBD", SBD);
			rates.put("SCR", SCR);
			rates.put("SDD", SDD);
			rates.put("SEK", SEK);
			rates.put("SGD", SGD);
			rates.put("SHP", SHP);
			rates.put("SIT", SIT);
			//			rates.put("SKK", SKK);
			rates.put("SLL", SLL);
			rates.put("SOS", SOS);
			rates.put("SRD", SRD);
			rates.put("STD", STD);
			rates.put("SVC", SVC);
			rates.put("SYP", SYP);
			rates.put("SZL", SZL);
			rates.put("THB", THB);
			rates.put("TJS", TJS);
			rates.put("TMM", TMM);
			rates.put("TND", TND);
			rates.put("TOP", TOP);
			rates.put("TRY", TRY);
			rates.put("TTD", TTD);
			rates.put("TWD", TWD);
			rates.put("TZS", TZS);
			rates.put("UAH", UAH);
			rates.put("UGX", UGX);
			rates.put("USD", USD);
			rates.put("USN", USN);
			rates.put("USS", USS);
			rates.put("UYU", UYU);
			rates.put("UZS", UZS);
			rates.put("VEB", VEB);
			rates.put("VND", VND);
			rates.put("VUV", VUV);
			rates.put("WST", WST);
			rates.put("XAF", XAF);
			rates.put("XCD", XCD);
			rates.put("XOF", XOF);
			rates.put("XPF", XPF);
			rates.put("YER", YER);
			rates.put("ZAR", ZAR);
			rates.put("ZMK", ZMK);
			rates.put("ZWD", ZWD);
		}
		return rates;
	}

	public Double getRate(String currency) {
		return getRates().get(currency);
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Rates [rates=");
		builder.append(getRates());
		builder.append("]");
		return builder.toString();
	}


}
